name: Build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build all targets
        run: ./gradlew buildAllTargets

      - name: Upload fabric-1.16.5 release
        uses: actions/upload-artifact@v4
        with:
          name: fabric-1.16.5-release
          path: fabric-1.16.5/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload fabric-1.18.2 release
        uses: actions/upload-artifact@v4
        with:
          name: fabric-1.18.2-release
          path: fabric-1.18.2/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload fabric-1.20.1 release
        uses: actions/upload-artifact@v4
        with:
          name: fabric-1.20.1-release
          path: fabric-1.20.1/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload forge-1.16.5 release
        uses: actions/upload-artifact@v4
        with:
          name: forge-1.16.5-release
          path: forge-1.16.5/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload forge-1.18.2 release
        uses: actions/upload-artifact@v4
        with:
          name: forge-1.18.2-release
          path: forge-1.18.2/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload forge-1.20.1 release
        uses: actions/upload-artifact@v4
        with:
          name: forge-1.20.1-release
          path: forge-1.20.1/build/libs/*[!-sources][!-shadow].jar
          if-no-files-found: error
          retention-days: 14
